---
- name: Include OS-specific variables (Debian).
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables (RedHat).
  ansible.builtin.include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
    - ansible_os_family == 'RedHat'

- name: Check if restic is installed
  ansible.builtin.stat:
    path: "{{ restic_path }}"
  register: restic_binary

- include_tasks: install.yml
  when: not restic_binary.stat.exists or restic_install

- name: Overwrite SSH config for backup server
  ansible.builtin.template:
    src: ssh_config.j2
    dest: "{{ restic_user_home }}/.ssh/config"
    owner: root
    group: root
    mode: "0600"
  when: restic_ssh_enabled

- name: Add SSH private key
  ansible.builtin.template:
    src: ssh_private_key.j2
    dest: "{{ restic_ssh_private_key_path }}"
    mode: "0600"
  when: restic_ssh_private_key is defined and restic_ssh_enabled

- name: Add restic_env in home folder
  ansible.builtin.template:
    src: restic_env.j2
    dest: "{{ restic_user_home }}/.restic_env"
    owner: root
    group: root
    mode: "0600"

- name: add ssh host
  ansible.builtin.known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: "{{ restic_ssh_hostname }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -p ' + restic_ssh_port | string + ' -H ' + restic_ssh_hostname ) }}"
  when: restic_ssh_enabled

- name: Add systemd service for restic
  ansible.builtin.template:
    src: restic-backup.service.j2
    dest: /etc/systemd/system/restic-backup.service
    mode: "0644"
  vars:
    restic_folders_combined: "{{ restic_default_folders + restic_folders }}"
  notify: systemd reload

- name: Add systemd timer for restic
  ansible.builtin.template:
    src: restic-backup.timer.j2
    dest: /etc/systemd/system/restic-backup.timer
    mode: "0644"
  notify: systemd reload

- name: Enable and start restic timer
  ansible.builtin.systemd:
    name: restic-backup.timer
    enabled: true
    state: started
